version: '3'
services:
  azure-vote-front:
    build:
      context: ./azure-vote
      target: development
    # ローカル環境のフォルダをコンテナにマウント
    volumes:
    - .:/app:rw
    - ~/.ssh:/root/.ssh:ro
    # - ./azure-vote/azure-vote:/app:rw
    # コンテナの実行をプロセスに依存せず永続化
    environment:
    - FLASK_ENV=development
    - FLASK_APP=main.py
    - PYHTONPATH=/app/azure-vote/azure-vote
    command: sleep infinity

